language: c
compiler: gcc

before_install:
    - sudo apt-get install python-software-properties
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update

install:
      
   #Source folder
    - PROJECT_DIR=$PWD

   #g++4.8 and gcc4.8
    - sudo apt-get install g++-4.8 
    - sudo apt-get install gcc-4.8
    - sudo rm /usr/bin/cpp /usr/bin/gcc /usr/bin/g++
    - sudo ln -s /usr/bin/cpp-4.8 /usr/bin/cpp
    - sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
    - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++

   #GMock
    - sudo apt-get install google-mock
    - cd /usr/src/ 
    - ls
    - cd gtest
    - ls
    - sudo cmake . 
    - sudo make 
    - ls
    - sudo cp -a *.a /usr/lib 

   #Gtest
    - sudo apt-get install libgtest-dev -y 
   
   
  # Fuentes de rocksdb
    - cd $PROJECT_DIR/otros/deps
    - sudo cp rocksdb.zip /usr/local/include
    - cd /usr/local/include
    - sudo unzip rocksdb.zip
    - sudo apt-get install libsnappy-dev zlib1g-dev libbz2-dev -y


   #LCOV
    #- sudo apt-get install lcov
    - sudo apt-get install ggcov
    - cd $PROJECT_DIR/otros/deps
    - tar -xzf lcov-1.10.tar.gz
    - cd lcov-1.10/
    - sudo make install
    - ll /usr/bin/gcov*
    - ll /usr/bin/lcov*
    - ll /usr/bin/gcc*
    - ll /usr/bin/g++*
    

   #Pip
    - cd $PROJECT_DIR/otros/deps
    - sudo python get-pip.py
    - sudo pip install requests
   
   #Update ld 
    - sudo ldconfig

script:
    - mkdir $PROJECT_DIR/src/UdriveServer/build
    - cd $PROJECT_DIR/src
    - cmake -DONLYTEST=ON UdriveServer/
    - make
    

