language: c
compiler: gcc
install:
        
   #Pip
   #- git clone https://bootstrap.pypa.io/get-pip.py
   #- sudo python get-pip.py
   #- pip install requests
   
    - sudo apt-get install cmake


before-script:

script:
    - ls
    - mkdir src/UdriveServer/main/build
    - cd src/UdriveServer/main/build
    - cmake -DONLYTEST=ON ..
    - make
    

