language: c
compiler: gcc
install:
        
   #Pip
   #- git clone https://bootstrap.pypa.io/get-pip.py
   #- sudo python get-pip.py
   #- pip install requests
   
   #g++4.8 
    - apt-get install python-software-properties
    - add-apt-repository ppa:ubuntu-toolchain-r/test
    - apt-get update
    - apt-get install g++-4.8
   
    - rm /usr/bin/cpp /usr/bin/gcc /usr/bin/g++
    
    - ln -s /usr/bin/cpp-4.8 /usr/bin/cpp
    - ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
    - ln -s /usr/bin/g++-4.8 /usr/bin/g++

   
   #CMAKE
    - apt-get install cmake


   #GMOCK 
    - apt-get install google-mock
    - cd /usr/src/gmock
    - sudo cmake .
    - sudo make
    - sudo cp -a *.a /usr/lib
    - cd /usr/src/gmock/gtest
    - sudo cp -a *.a /usr/lib

   #LCOV
    - apt-get install lcov

script:
    - ls
    - mkdir src/UdriveServer/main/build
    - cd src/UdriveServer/main/build
    - cmake -DONLYTEST=ON ..
    - make
    

