language: c
compiler: gcc
install:
        
   #Pip
   #- git clone https://bootstrap.pypa.io/get-pip.py
   #- sudo python get-pip.py
   #- pip install requests

   #Udrive
   - cd src/
   - ll

before-script:
    - mkdir src/UdriveServer/main/build

script:
    - cd src/UdriveServer/main/build
    - cmake -DONLYTEST=ON ..
    - make
    

