language: c
compiler: gcc

before_install:
    - sudo apt-get install python-software-properties
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update

install:
      

    - PROJECT_DIR=$PWD

   #g++4.8 

    - sudo apt-get install g++-4.8
   
    - sudo rm /usr/bin/cpp /usr/bin/gcc /usr/bin/g++
    
    - sudo ln -s /usr/bin/cpp-4.8 /usr/bin/cpp
    - sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
    - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++

   #GTEST
    - cd $PROJECT_DIR/otros/deps
    - unzip gtest-1.7.0.zip
    - cd gtest-1.7.0
    - mkdir build
    - cd build/
    - cmake ..
    - make
    - cd ..
    - ls
    #- cd lib/
    #- ls
    #- sudo cp -a *.la /usr/lib
    #- ls /usr/lib
    #- cd /usr/include/
    #- sudo mkdir gtest
    #- cd $PROJECT_DIR/otros/deps/gtest-1.7.0/include/gtest/
    #- sudo cp -a . /usr/include/gtest/

   #GMOCK 
    - cd $PROJECT_DIR/otros/deps
    - unzip gmock-1.7.0.zip
    - cd gmock-1.7.0
    - mkdir build
    - cd build/
    - cmake ..
    - make
    #- cd ../lib
    #- ls
    #- sudo cp *.la /usr/lib
    #- cd /usr/include/
    #- sudo mkdir gmock
    #- cd $PROJECT_DIR/otros/deps/gmock-1.7.0/include/gmock/
    #- sudo cp -a . /usr/include/gmock/

   # Fuentes de rocksdb
    - cd $PROJECT_DIR/otros/deps
    - sudo cp rocksdb.zip /usr/local/include
    - cd /usr/local/include
    - sudo unzip rocksdb.zip


   #LCOV
    - sudo apt-get install lcov

   #Pip
    - cd $PROJECT_DIR/otros/deps
    - sudo python get-pip.py
    - sudo pip install requests
   
    - sudo ldconfig

script:
    - mkdir $PROJECT_DIR/src/UdriveServer/build
    - cd $PROJECT_DIR/src/UdriveServer/build
    - cmake -DONLYTEST=ON ..
    - make
    

