language: c
compiler: gcc

before_install:
    - sudo apt-get install python-software-properties
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update

install:
      

    - PROJECT_DIR=$PWD

   #g++4.8 

    - sudo apt-get install g++-4.8
   
    - sudo rm /usr/bin/cpp /usr/bin/gcc /usr/bin/g++
    
    - sudo ln -s /usr/bin/cpp-4.8 /usr/bin/cpp
    - sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
    - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++

   
   #CMAKE
    - sudo apt-get install cmake

   # Fuentes de rocksdb
    - cd $PROJECT_DIR/otros/deps
    - sudo cp rocksdb.zip /usr/local/include
    - cd /usr/local/include
    - sudo unzip rocksdb.zip

   #GMOCK 
    - cd $PROJECT_DIR/otros/deps
    - unzip gmock-1.7.0.zip
    - cd gmock-1.7.0
    - ./configure
    - make
    - sudo cp *.a /usr/lib
    - cd /usr/include/
    - mkdir gmock
    - cd /opt/gmock-1.7.0/include/gmock/
    - sudo cp -a . /usr/include/gmock/

   #GTEST
    - cd $PROJECT_DIR/otros/deps
    - unzip gtest-1.7.0.zip
    - cd gtest-1.7.0
    - ./configure
    - make
    - sudo cp *.a /usr/lib
    - cd /usr/include/
    - mkdir gtest
    - cd /opt/gtest-1.7.0/include/gtest/
    - sudo cp -a . /usr/include/gtest/

   #LCOV
    - sudo apt-get install lcov

   #Pip
    - cd $PROJECT_DIR/otros/deps
    - sudo python get-pip.py
    - pip install requests
   

script:
    - mkdir src/UdriveServer/build
    - cd src/UdriveServer/build
    - cmake -DONLYTEST=ON ..
    - make
    

