language: c
compiler: gcc

before_install:
    - sudo apt-get install python-software-properties
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update

install:
        
   #Pip
   #- git clone https://bootstrap.pypa.io/get-pip.py
   #- sudo python get-pip.py
   #- pip install requests
   
   #g++4.8 

    - sudo apt-get install g++-4.8
   
    - sudo rm /usr/bin/cpp /usr/bin/gcc /usr/bin/g++
    
    - sudo ln -s /usr/bin/cpp-4.8 /usr/bin/cpp
    - sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
    - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++

   
   #CMAKE
    - sudo apt-get install cmake


   #GMOCK 
    - cd otros/deps
    - unzip gmock-1.7.0.zip
    - cd gmock-1.7.0
    - ./configure
    - make
    - cd ../../..

   #GTEST
    - cd otros/deps
    - unzip gtest-1.7.0.zip
    - cd gtest-1.7.0
    - ./configure
    - make
    - cd ../../..

   #LCOV
    - sudo apt-get install lcov

script:
    - ls
    - mkdir src/UdriveServer/build
    - cd src/UdriveServer/build
    - cmake -DONLYTEST=ON ..
    - make
    

