language: c
compiler: gcc
install:
        
   #Pip
   #- git clone https://bootstrap.pypa.io/get-pip.py
   #- sudo python get-pip.py
   #- pip install requests


before-script:
   - mkdir tp_taller2/src/UdriveServer/main/build
script:
    - ls
    - cd tp_taller2/src/UdriveServer/main/build
    - cmake -DONLYTEST=ON ..
    - make
    

