language: c
compiler: gcc
install:
        
   #Pip
   #- git clone https://bootstrap.pypa.io/get-pip.py
   #- sudo python get-pip.py
   #- pip install requests
   
   #g++4.8 
    - sudo apt-get install python-software-properties
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install g++-4.8
   
   #CMAKE
   - sudo apt-get install cmake


before-script:

script:
    - ls
    - mkdir src/UdriveServer/main/build
    - cd src/UdriveServer/main/build
    - cmake -DONLYTEST=ON ..
    - make
    

